name: Gerar Executável Windows

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Baixar código do repositório
      uses: actions/checkout@v4  # Atualizado de v3 para v4

    - name: Configurar Python
      uses: actions/setup-python@v5 # Atualizado de v4 para v5
      with:
        python-version: '3.12'

    - name: Instalar bibliotecas
      run: |
        python -m pip install --upgrade pip
        pip install customtkinter matplotlib 

    - name: Gerar .exe com PyInstaller
      run: |
        pip install pyinstaller
        pyinstaller --noconsole --onefile main.py

    - name: Guardar o executável
      uses: actions/upload-artifact@v4 # Atualizado de v3 para v4 (O erro estava aqui!)
      with:
        name: SistemaFinanceiro-Windows
        path: dist/main.exe